development:
  adapter: postgresql
  database: beacon_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: beacon_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: beacon_production
  pool: 5
  timeout: 5000
